#!/bin/sh

playerctl --no-messages --follow metadata --format '{"artist": "{{ artist }}", "title": "{{ title }}", "album": "{{ album }}", "cover": "{{ mpris:artUrl }}",  "status": "{{ status }}", "length": "{{ mpris:length }}"}' | while read -r LINE; do
    if [ -z "$LINE" ]; then
        echo '{"artist": "", "title": "", "album": "", "cover": "", "status": "", "length": ""}'
    else
        cover=$(jq -r '.cover' <<< "$LINE")
    
        file="/tmp/covers/$(cat /proc/sys/kernel/random/uuid).jpg"

        rm -f /tmp/covers/*
        curl -s --create-dirs "$cover" -o "$file"
        echo $(jq ".cover = \"$file\"" <<< "$LINE")
    fi
done