#!/bin/sh

get_volume()
{
  volume=$(pamixer --get-volume)
  mute=$(pamixer --get-mute)
  sinks=$(pactl -f json list sinks | jq -c '[ .[] | {name: .name, description: .properties."alsa.card_name"} ]')
  default=$(pactl get-default-sink)
  icon=""

  if [ "$mute" == true ]; then
    icon=""
  elif [ "$volume" -gt 75 ]; then
    icon=""
  elif [ "$volume" -gt 50 ]; then
    icon=""
  elif [ "$volume" -gt 25 ]; then
    icon=""
  else
    icon=""
  fi

  printf '{"volume": %d, "mute": %s, "sinks": %s, "default": "%s", "icon": "%s"}\n' "$volume" "$mute" "$sinks" "$default" "$icon"
}

get_volume

pactl subscribe | while read x event y type num; do
  if [ "$event" == '“alterar”' ] && [ "$type" == "destino" ]; then
    get_volume
  fi
done
