#!/bin/sh

get_details()
{
  type=$(hostname | grep -qF 'desktop' && echo 'lan' || echo 'wifi')

  if [ "$type" = "wifi" ]; then
    DEVICE="wlo1"

    enabled=$(nmcli radio wifi | awk '{print $0 == "enabled"}')
  else
    DEVICE="enp4s0"

    enabled=1
  fi

  data=$(nmcli device show $DEVICE)
  state=$(echo "$data" | grep 'GENERAL.STATE' | awk '{printf "%d", $2}')
  network=$(echo "$data" | grep 'GENERAL.CONNECTION' | awk '{printf "%s", $2}')

  status=""
  if [ "$state" -eq 100 ]; then
    status="connected"
  elif [ "$state" -ge 50 ] && [ $state -lt 100 ]; then
    status="connecting"
  else
    status="disconnected"
    network="Disconnected"
  fi

  printf '{"type": "%s", "enabled": %d, "status": "%s", "network": "%s"}\n' "$type" "$enabled" "$status" "$network"
}

get_details

nmcli monitor | while read -r LINE; do
  if [[ "$LINE" == *"$DEVICE"* ]]; then
    get_details
  fi
done