#!/bin/sh

NUMBER_OF_WORKSPACES=9

window_class() {
    echo `hyprctl activewindow -j | jq --raw-output .class`
}

window_title() {
    echo `hyprctl activewindow -j | jq --raw-output .title`
}

workspaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    seq 1 $NUMBER_OF_WORKSPACES | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}
active=1
if [[ $1 == 'workspaces' ]]; then 
    echo "{ \"workspaces\": $(workspaces), \"active\": $active }"
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        if [[ ${line:0:9} == 'workspace' ]]; then
            active=${line:11:2}
        fi

        echo "{ \"workspaces\": $(workspaces), \"active\": $active }"
    done
fi

if [[ $1 == 'window' ]]; then 
    window_class
    socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
        window_class
    done
fi
