[general]
import = ["/home/tiago/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
title = "Terminal"

[window.padding]
x = 10
y = 10
