#!/bin/sh

command=$1
window=$2

if [[ "$command" == "open" ]]; then
  if [[ ! "$(eww windows)" =~ "*$window" ]]; then
    screen=0

    $(eww update openmenu="$window")
    $(eww open --screen "$screen" closer)
    $(eww open --screen "$screen" "$window")
  fi
else
  $(eww update openmenu="")
  $(eww close "$window")
  $(eww close closer)

  if [[ $window == "wifimenu" ]]; then
    $(eww update wifishowlist=false)

    if [ $(eww windows | grep '*wifipassword') ]; then
      $(eww close wifipassword)
    fi
  fi
fi
